---
title: "QMF Final Presentation"
author: "Ajay Dugar"
date: "12/16/2020"
output: html_document
---

```{r}
library(tidyquant)
library(TTR)
library(latex2exp)
```

```{r}
# Slide 4
one_ticker = tq_get("^GSPC", from = "1900-01-01")
sp500_daily = diff(log(one_ticker$adjusted), lag = 1, differences = 1)
plot(density(sp500_daily), main="PDF of S&P 500 Daily Log-Returns (1927-2020)", xlab = "Returns")
x = seq(-3, 3, by = 0.01)
y2 = dnorm(x, mean = mean(exp(sp500_daily)-1), sd = sd(exp(sp500_daily)-1)) # Simple returns (Arithmetic Brownian Motion)
lines(x, y2, type = "l", col = "red")
legend(-0.22, 30, legend=c("S&P 500 Log-Returns", "Normal Distribution of Simple Returns"), col=c("black", "red"), lty=1, cex=0.8)
```

```{r}
# Slide 5 Top
one_ticker = tq_get("^GSPC", from = "1900-01-01")
sp500_daily = diff(log(one_ticker$adjusted), lag = 1, differences = 1)
plot(density(sp500_daily), main="PDF of S&P 500 Daily Log-Returns (1927-2020)", xlab = "Returns")
x = seq(-3, 3, by = 0.01)
y = dnorm(x, mean = mean(sp500_daily), sd = sd(sp500_daily))
lines(x, y, type = "l", col = "blue") 
legend(-0.2, 30, legend=c("S&P 500 Returns", "Normal Distribution of Log-Returns"), col=c("black", "blue"), lty=1, cex=0.8)
```


```{r}
# Slide 5 Bottom
one_ticker = tq_get("^GSPC", from = "1900-01-01")
sp500_daily = diff(log(one_ticker$adjusted), lag = 1, differences = 1)
plot(density(sp500_daily)$x, log(density(sp500_daily)$y), main="PDF of S&P 500 Daily Log-Returns (1927-2020)", xlab = "Returns", ylab = "log(density)", type = "l", ylim = c(-100, 10))
x = seq(-3, 3, by = 0.01)
y = dnorm(x, mean = mean(sp500_daily), sd = sd(sp500_daily))
lines(x, log(y), type = "l", col = "blue") 
legend(-0.1, -80, legend=c("S&P 500 Returns", "Normal Distribution of Log-Returns"), col=c("black", "blue"), lty=1, cex=0.8)
```

```{r}
# Slide 7 Bottom
x = seq(0, 5, length.out = 200)
y1 = dexp(x, rate = 0.5)
y2 = dexp(x, rate = 1)
y3 = dexp(x, rate = 1.5)
plot(x, y1, type = "l", ylim = c(0, 1.6), xlim = c(0, 3), ylab = "P(x)", xlab = "x", col = "red", main = TeX("Exponential Distributions with different $\\lambda"))
lines(x, y2, type = "l", col = "green")
lines(x, y3, type = "l", col = "blue")
legend(1, 1.5, legend=c(TeX("$\\lambda = 0.5"), TeX("$\\lambda = 1.0"), TeX("$\\lambda = 1.5")), col=c("red", "green", "blue"), lty=1, cex=0.8)
```


```{r}
sp500 = one_ticker$adjusted[17000:20000]
arith_sp500 = c()
geo_sp500 = c()
for (i in 1:length(sp500)){
  arith_sp500[i] = mean(sp500[1:i])
  geo_sp500[i] = exp(mean(log(sp500[1:i])))
}
```

```{r}
plot(sp500, type = "l")
lines(arith_sp500, type = "l", col = "blue")
lines(geo_sp500, type = "l", col = "red")
legend(0, 1500, legend=c("S&P 500", "Arithmetic Mean", "Geometric Mean"), col=c("black", "blue", "red"), lty=1, cex=0.8)
```

